Controllers/EmployerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HomeCare.Data;
using HomeCare.Models;

namespace HomeCare.Controllers
{
    public class EmployerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmployerController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Employer
        public async Task<IActionResult> Index()
        {
            return RedirectToAction(nameof(HomeController.Index));
        }

        // GET: Employer/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employerModel = await _context.Employer
                .SingleOrDefaultAsync(m => m.Id == id);
            if (employerModel == null)
            {
                return NotFound();
            }

            return View(employerModel);
        }

        // GET: Employer/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Surname,Firstname,Lastname,Gender,Religion,Occupation,HomeAddress,OfficeAddress,LGA,State,Country,Phone,Email,Photo")] EmployerModel employerModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employerModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employerModel);
        }

        // GET: Employer/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employerModel = await _context.Employer.SingleOrDefaultAsync(m => m.Id == id);
            if (employerModel == null)
            {
                return NotFound();
            }
            return View(employerModel);
        }

        // POST: Employer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Surname,Firstname,Lastname,Gender,Religion,Occupation,HomeAddress,OfficeAddress,LGA,State,Country,Phone,Email,Photo")] EmployerModel employerModel)
        {
            if (id != employerModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employerModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployerModelExists(employerModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employerModel);
        }

        // GET: Employer/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employerModel = await _context.Employer
                .SingleOrDefaultAsync(m => m.Id == id);
            if (employerModel == null)
            {
                return NotFound();
            }

            return View(employerModel);
        }

        // POST: Employer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employerModel = await _context.Employer.SingleOrDefaultAsync(m => m.Id == id);
            _context.Employer.Remove(employerModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployerModelExists(int id)
        {
            return _context.Employer.Any(e => e.Id == id);
        }
    }
}

Controllers/GuarantorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HomeCare.Data;
using HomeCare.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace HomeCare.Controllers
{
    public class GuarantorController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public GuarantorController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Guarantor
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ViewHelpers()
        {
            var user = await _userManager.GetUserAsync(User);
            return View(await _context.Helper.Where(c => c.Guarantor.Id.Equals(user.Id)).ToListAsync());
        }

        // GET: Guarantor/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guarantorModel = await _context.Guarantor
                .SingleOrDefaultAsync(m => m.Id == id);
            if (guarantorModel == null)
            {
                return NotFound();
            }

            return View(guarantorModel);
        }

        [Authorize]
        // GET: Guarantor/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Guarantor/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,HomeAddress,OfficeAddress,LGA,State,Country,Phone,Email,Surname,Firstname,Lastname,Gender,Religion,CreatedAt,UpdatedAt")] GuarantorModel guarantorModel,IFormFile photo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(guarantorModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(guarantorModel);
        }

        // GET: Guarantor/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guarantorModel = await _context.Guarantor.SingleOrDefaultAsync(m => m.Id == id);
            if (guarantorModel == null)
            {
                return NotFound();
            }
            return View(guarantorModel);
        }

        // POST: Guarantor/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,HomeAddress,OfficeAddress,LGA,State,Country,Phone,Email,Photo,Surname,Firstname,Lastname,Gender,Religion,CreatedAt,UpdatedAt")] GuarantorModel guarantorModel)
        {
            if (id != guarantorModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(guarantorModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GuarantorModelExists(guarantorModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(guarantorModel);
        }

        // GET: Guarantor/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guarantorModel = await _context.Guarantor
                .SingleOrDefaultAsync(m => m.Id == id);
            if (guarantorModel == null)
            {
                return NotFound();
            }

            return View(guarantorModel);
        }

        // POST: Guarantor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var guarantorModel = await _context.Guarantor.SingleOrDefaultAsync(m => m.Id == id);
            _context.Guarantor.Remove(guarantorModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GuarantorModelExists(int id)
        {
            return _context.Guarantor.Any(e => e.Id == id);
        }
    }
}

Controllers/HelperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HomeCare.Data;
using HomeCare.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace HomeCare.Controllers
{
    [Authorize(Roles = ""+AppUtils.AppRoles.ADMIN+","+AppUtils.AppRoles.GUARANTOR+"")]
    public class HelperController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public HelperController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Helper
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            
            if(User.IsInRole(AppUtils.AppRoles.ADMIN))   return View(await _context.Helper.ToListAsync());

            return View(await _context.Helper.Where(c => c.Guarantor.UserId.Equals(userId)).ToListAsync());
        }

        // GET: Helper/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var helperModel = await _context.Helper
                .SingleOrDefaultAsync(m => m.Id == id);
            if (helperModel == null)
            {
                return NotFound();
            }

            return View(helperModel);
        }

        // GET: Helper/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Helper/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Surname,Firstname,Lastname,Gender,Religion,Qualification,Language,Status,NextOfKinName,NextOfKinAddress,NextOfKinPhone")] HelperModel helperModel)
        {
            var userId = _userManager.GetUserId(User);

            if (ModelState.IsValid)
            {
                var staffId = _context.Guarantor.SingleOrDefault(c => c.UserId.Equals(userId)).Id;
                helperModel.GurantorId = staffId;

                _context.Add(helperModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(helperModel);
        }

        // GET: Helper/Edit/5
        [Authorize(Roles = AppUtils.AppRoles.GUARANTOR)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var helperModel = await _context.Helper.SingleOrDefaultAsync(m => m.Id == id);
            if (helperModel == null)
            {
                return NotFound();
            }
            return View(helperModel);
        }

        // POST: Helper/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Surname,Firstname,Lastname,Gender,Religion,Qualification,Language,Status,NextOfKinName,NextOfKinAddress,NextOfKinPhone")] HelperModel helperModel)
        {
            if (id != helperModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(helperModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HelperModelExists(helperModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(helperModel);
        }

        // GET: Helper/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var helperModel = await _context.Helper
                .SingleOrDefaultAsync(m => m.Id == id);
            if (helperModel == null)
            {
                return NotFound();
            }

            return View(helperModel);
        }

        // POST: Helper/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var helperModel = await _context.Helper.SingleOrDefaultAsync(m => m.Id == id);
            _context.Helper.Remove(helperModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HelperModelExists(int id)
        {
            return _context.Helper.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using HomeCare.AppUtils
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeCare</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">HomeCare.com</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    @if (!SignInManager.IsSignedIn(User))
                    {
                        <li><a asp-area="" asp-controller="Guarantor" asp-action="Create">Join Providers</a></li>
                    }

                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>

                    @if (User.IsInRole(AppRoles.EMPLOYER))
                    {
                        <li><a asp-area="" asp-controller="Employer" asp-action="Edit">Update Profile</a></li>
                        @*<li><a asp-area="" asp-controller="Employer" asp-action="About">Register Helper</a></li>*@
                        <li><a asp-area="" asp-controller="Employer" asp-action="Contact">Check Lists</a></li>
                    }

                    @if (User.IsInRole(HomeCare.AppUtils.AppRoles.GUARANTOR))
                    {
                        <li><a asp-area="" asp-controller="Guarantor" asp-action="Edit">My Profile</a></li>
                        <li><a asp-area="" asp-controller="Helper" asp-action="Create">Register Helper</a></li>
                        <li><a asp-area="" asp-controller="Guarantor" asp-action="ViewHelpers">View Employers</a></li>
                    }

                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    @*<nav class="navbar navbar-text navbar-link">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><b>Search By</b></li>
                <li>Male</li>
                <li>Female</li>
                <li><select name="state">
                        <option value="Abia">Abia</option>
                        <option value="Adamawa">Adamawa</option>
                        <option value="Akwa-Ibom">Akwa-Ibom</option>
                        <option value="Anambra">Anambra</option>
                        <option value="Bauchi">Bauchi</option>
                        <option value="Benue">Benue</option>
                    </select>
                </li>
            </ul>
        </div>
    </nav>*@
    <div class="container body-content">
        
        <hr />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - HomeCare</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>